### ISSUE TITLE
Setup Gradle build

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#10]
We should setup the Gradle build to follow the conventions in [Spring Security](https://github.com/spring-projects/spring-security).

The gradle build should support the following modules:

`core` module with base package -> `org.springframework.security.oauth2.server.authorization`
`config` module with base package -> `org.springframework.security.config`
`samples` module

**Comment by jbellmann** [comment]
Hello, I would like to contribute here, but I'm not sure to start because there are already 2 PRs (#23 and  #24 ) open that contradict somehow to what is required in this ticket, a multi-module setup.
What is recommended, wait until #23 or #24 are merged or creating a PR based on what is currently in master?

At the moment it looks like people want to help/contribute from outside but without clear structure.

@jgrandja 
@eleftherias

**Comment by jgrandja** [comment]
Thanks for reaching out @jbellmann. We're going to hold off on the main project gradle build for now until we actually have framework code to build against. We're starting off with samples #19 and next week I'll have another epic setup for the `authorization_code` grant sample. At that point, we'll have some more issues that can be worked on and more structure to the project plan. It would be great if you can reach out next week after you review the new issues. Sounds good?
