### ISSUE TITLE
Register SecurityFilterChain instead of WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#163]
Instead of extending `WebSecurityConfigurerAdapter`, we should use the new method of registering a `SecurityFilterChain` `@Bean`.

**Comment by ShannonHung** [comment]
i am curious how to configure AuthenticationManagerBuilder without extends WebSecurityConfigurerAdapter.
I am facing the same question about IllegalStateException when using WebSecurityConfigurerAdapter.
Because I want to use my own UserDetailsService. But i have no idea to set the userDetailsService by SecurityFilterChain.
```
@Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.userDetailsService(userDetailService)
                .passwordEncoder(new BCryptPasswordEncoder());
    }
```
