### ISSUE TITLE
Extension point to limit the scopes granted to a token

### ISSUE THREAD

**Issue by metacubed** [spring-projects-experimental/spring-authorization-server#218]
When a token is generated for either client- or user-based grants, it would be useful to provide a generic mechanism to reduce<sup>++</sup> the scopes which are present in the granted JWT.

The list of granted scopes starts with those available to the client. This list can be reduced by many different kinds of constraints. These are just a few examples (not an exhaustive list):

- The resource-owner consenting to only a subset of scopes
- The `scope` claim in the token request (#212)
- Custom policies defined in a larger authorization-server product (#187)

I would propose injecting a chain of `TokenScopeCustomizer` implementations, which take in the initial token request and the initial granted list of scopes, and returning a subset of those scopes at the end of the chain.

<br/>
<sup>++</sup> I think it is reasonable to only <i>reduce</i> the available scopes, not add to them. However, it might turn out that there are use cases for both.

**Comment by metacubed** [comment]
Does this seem reasonable, @jgrandja? I can give this a try if it fits the overall design.

**Comment by jgrandja** [comment]
Thanks for the details @metacubed.

I agree that we do need the capability to restrict/reduce/add scopes and/or claims during the authorization process. I have captured this in #139 at a very high level:

> Provide plugin mechanism for Policy Enforcement

Instead of a `TokenScopeCustomizer`, I would prefer to design a high-level abstraction around Policy Enforcement so it can fulfill many uses cases.

Would you mind logging the details in this ticket over to #139 and close this one? I'd like to have all the information captured there.

Before we start work on a Policy Enforcement abstraction, some R&D work needs to be performed on existing providers to understand how they have implemented. Would you be interested in doing some R&D so we can learn more on what design would work best?

**Comment by metacubed** [comment]
Reworded and moved over to the umbrella ticket [here](https://github.com/spring-projects-experimental/spring-authorization-server/issues/139#issuecomment-780925433).

Re. a single interface for all token customization, not sure if that will help or harm usability. I can see it becoming quite intimidating 😄.

And yes, let me know how I can help with the Policy Enforcement investigation, @jgrandja.

**Comment by jgrandja** [comment]
Thanks @metacubed.

I just realized that the recently added `OAuth2TokenCustomizer` could very well realize your use case.

A `@Bean` of type `OAuth2TokenCustomizer<JwtEncodingContext>` will allow you to customize the `scope` claim in the `Jwt`. 

Follow the conversation in this [thread](https://github.com/spring-projects-experimental/spring-authorization-server/issues/199#issuecomment-773554288) to see examples on how to customize a `Jwt`.

Please let me know if this worka for your use case.
