### ISSUE TITLE
How can i implement Single Sign On with multiple login ways ?

### ISSUE THREAD

**Issue by gth7754125** [spring-projects-experimental/spring-authorization-server#242]
**Describe the Problem**
This project seems to put all OAuth2 logic to Security Filter Chain.
So how can i put my login Apis such as **Username/Password** / **third Party Platform Scan Code** etc with the chain ?
It seems not suitable to write my code on Controller Layer.

**Expected behavior**
Can i use some exposed Services to write my code ?
Or some other way to put my custom login logic to implement SSO.

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
