### ISSUE TITLE
Roadmap for production use

### ISSUE THREAD

**Issue by Ravis22** [spring-projects-experimental/spring-authorization-server#310]
Hi Team,
   I wish to know what is the plan for having release that is ready for production use.

**Comment by sjohnr** [comment]
Hi @Ravis22. I don't have any specifics at this time. In the near term, please keep an eye on [0.1.2](https://github.com/spring-projects-experimental/spring-authorization-server/milestone/6) and [0.2.0](https://github.com/spring-projects-experimental/spring-authorization-server/milestone/7) milestones as they progress in the coming months.

You can also check out recent and ongoing work for clients, authorizations and consents using JDBC instead of in-memory as these are an important part of the 0.1.2 target: #265, #245, #313.

Also, keep an eye on [spring.io/blog/category/releases](https://spring.io/blog/category/releases) (similar question [here](http://disq.us/p/2f7og2q)). We will definitely provide updates there as they become available.

**Comment by jgrandja** [comment]
@Ravis22 We are targeting the upcoming `0.2.0` release to be production-ready.
