### ISSUE TITLE
OAuth2Authorization Token throws ClassCastException when isBeforeUse is called

### ISSUE THREAD

**Issue by jrmcdonald** [spring-projects-experimental/spring-authorization-server#332]
**Describe the bug**
I think the cast of the token metadata to (Instant) in [OAuth2Authorization.Token#isBeforeUse]() can cause a class cast exception when used in conjunction with the newly implemented JdbcOAuth2AuthorizationService.

**To Reproduce**
The JDBC implementation writes the token metadata to the database as a string, using ObjectMapper to transform the map of metadata. This means that data types such as `Instant` get transformed into their String representation when stored in the database (i.e. "2021-06-29T09:24:19.055Z"). When the metadata is read from the database and reconstructed into a `Map<String, Object>`, the value which was previously an `Instant` is now just a `String`.

If we take a client credentials access token as an example (as created by OAuth2ClientCredentialsAuthenticationProvider), the token metadata contains a key for `metadata.token.claims` which is another Map<String, Object> containing the JWT claims. This may contain an `nbf` claim which is initially created as an Instant.

The access token metadata is transformed in [JdbcOAuth2AuthorizationService.java#L536](https://github.com/spring-projects-experimental/spring-authorization-server/blob/232b3b7ac6ff6d4eb465d3219c823d4cfd3fa01c/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/JdbcOAuth2AuthorizationService.java#L536) before being stored in the database. If you then retrieve that authorization, get the access token, and call the [isBeforeUse](https://github.com/spring-projects-experimental/spring-authorization-server/blob/232b3b7ac6ff6d4eb465d3219c823d4cfd3fa01c/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/OAuth2Authorization.java#L302) method you will get a class cast exception because the nbf is stored as a String now, not an Instant.

**Expected behavior**
The isBeforeUse method could check whether the object is an instance of Instant before casting, or attempt to parse a String value into an Instant.

I don't currently have an easily viewable sample, but I can try to put one together if needed.

**Comment by sjohnr** [comment]
@jrmcdonald, I believe this bug was filed based on the initial implementation prior to 232b3b7ac6ff6d4eb465d3219c823d4cfd3fa01c, which supports proper serialization. You can check out e.g. [OAuth2TokenIntrospectionTests.java#L155](https://github.com/spring-projects-experimental/spring-authorization-server/blob/41dd68903c5b3401009253712f3a581024234668/oauth2-authorization-server/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2TokenIntrospectionTests.java#L155) which tests this and reads back in metadata serialized as json, where it properly converts from `OAuth2AccessToken` -> json in db w/`Instant` in metadata -> `OAuth2AccessToken`.

Here is an example of how the metadata is serialized now, so that it is properly read back in as an `Instant`:

```json
{
  "@class": "java.util.Collections$UnmodifiableMap",
  "metadata.token.claims": {
    "@class": "java.util.Collections$UnmodifiableMap",
    "sub": "client-2",
    "aud": [
      "java.util.Collections$SingletonList",
      [
        "client-2"
      ]
    ],
    "nbf": [
      "java.time.Instant",
      1625676140.561006000
    ],
    "scope": [
      "java.util.LinkedHashSet",
      [
        "scope1",
        "scope2"
      ]
    ],
    "exp": [
      "java.time.Instant",
      1625676440.561006000
    ],
    "iat": [
      "java.time.Instant",
      1625676140.561006000
    ],
    "jti": "36ff89d2-17be-42e4-b36d-098810e0a311"
  },
  "metadata.token.invalidated": false
}
```

I'm going to close this for now. If I missed anything or you notice anything is still off, please feel free to reopen.

**Comment by jrmcdonald** [comment]
Hi @sjohnr, thanks for such a detailed response. That definitely sounds like it fixes the issue as I described it!
