### ISSUE TITLE
 How does Chunyun Gateway integrate?

### ISSUE THREAD

**Issue by mpv945** [spring-projects-experimental/spring-authorization-server#345]
At present, we are ready to upgrade the boot to version 2.5.2. 
Can there be examples for the unified authentication and authorization of the microservice architecture gateway?

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it).
