### ISSUE TITLE
Authorization Server 0.1.2 - On startup The Apache Tomcat Native library could not be found using names

### ISSUE THREAD

**Issue by neblaz** [spring-projects-experimental/spring-authorization-server#390]
I tried a Spring Security OAuth2 example from here
https://www.baeldung.com/spring-security-oauth-auth-server
https://github.com/Baeldung/spring-security-oauth/tree/master/oauth-authorization-server

and with 0.1.2 I get on startup an error
main] o.a.catalina.core.AprLifecycleListener   : The Apache Tomcat Native library could not be found using names...

as described here
https://stackoverflow.com/questions/68693085/spring-security-oauth-2-authorization-server-update-from-0-1-0-to-0-1-1-0-1

**Comment by jgrandja** [comment]
Thanks for getting in touch @neblaz, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.

It seems the issue is environment related. The [sample](https://github.com/spring-projects-experimental/spring-authorization-server/tree/main/samples/boot/oauth2-integration) runs without issue.
